package controller

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"sync"

	"github.com/gorilla/mux"
	// gin-swagger middleware
	// swagger embed files
	// docs is generated by Swag CLI, you have to import it.

	//jwt
	jwt "github.com/dgrijalva/jwt-go"
)

var signingKey = os.Getenv("MY_JWT")

// isAuthorized() validates the token in the header and if so calls the endpoint
func isAuthorized(endpoint func(http.ResponseWriter, *http.Request)) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Header["Token"] != nil {

			token, err := jwt.Parse(r.Header["Token"][0], func(token *jwt.Token) (interface{}, error) {
				if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
					return nil, fmt.Errorf("There was an error")
				}
				return signingKey, nil
			})
			if err != nil {
				fmt.Fprintf(w, err.Error())
			}
			if token.Valid {
				endpoint(w, r)
			}
		} else {
			fmt.Fprintf(w, "Not Authorized")
		}
	})
}

// homePage() to handle all request to root URL
func homePage(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Welcome to the Homepage!")
	fmt.Println("Endpoint Hit: homepage")
}

// returnArticles() returns all articles
func returnArticles(w http.ResponseWriter, r *http.Request) {
	fmt.Println("Endpoint Hit: returnArticles")

	json.NewEncoder(w).Encode(Articles)
}

// returnArticle() returns particualr article matching {id}
func returnSingleArticle(w http.ResponseWriter, r *http.Request) {
	fmt.Println("Endpoint Hit: returnSingleArticle")

	vars := mux.Vars(r)
	key := vars["id"]

	for _, article := range Articles {
		if article.Id == key {
			json.NewEncoder(w).Encode(article)
		}
	}
}

// createNewArticle() creates a new article
func createNewArticle(w http.ResponseWriter, r *http.Request) {
	fmt.Println("Endpoint Hit: createNewArticle")
	reqBody, _ := ioutil.ReadAll(r.Body)

	fmt.Fprintf(w, "%+v", string(reqBody))
	fmt.Printf("Post Reuqst Body %v\n", string(reqBody))

	var article Article

	err := json.Unmarshal(reqBody, &article)
	if err != nil {
		log.Fatalf("Failed to Unmarshal request body %v", err)
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte("500 - Create new Article Failed due to some error"))
	}
	Articles = append(Articles, article)
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("200  Create article successful"))
	json.NewEncoder(w).Encode(article)
}

// createNewArticleV2() creates a new article
func createNewArticleV2(w http.ResponseWriter, r *http.Request) {
	fmt.Println("Endpoint Hit: createNewArticle")
	reqBody, _ := ioutil.ReadAll(r.Body)

	fmt.Fprintf(w, "%+v", string(reqBody))
	fmt.Printf("Post Reuqst Body %v\n", string(reqBody))

	var article Article

	err := json.Unmarshal(reqBody, &article)
	if err != nil {
		log.Fatalf("Failed to Unmarshal request body %v", err)
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte("500 - Create new Article Failed due to some error"))
	}
	Articles = append(Articles, article)
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("200 - Create new Article Successful"))
	json.NewEncoder(w).Encode(article)
}

// deleteArticle() deletes an article
func deleteArticle(w http.ResponseWriter, r *http.Request) {
	fmt.Println("Endpoint Hit: deleteArticle")

	vars := mux.Vars(r)

	id := vars["id"]

	for index, article := range Articles {
		if article.Id == id {
			Articles = append(Articles[:index], Articles[index+1:]...)
			w.WriteHeader(http.StatusOK)
			w.Write([]byte("200 - Delete article successful"))
		} else {
			log.Println("Record not found")
			w.WriteHeader(http.StatusInternalServerError)
			w.Write([]byte("500 - Delete article failed due to some error"))
		}
	}
}

// updateArticle() update existing article id
func updateArticle(w http.ResponseWriter, r *http.Request) {
	fmt.Println("Endpoint Hit: updateArticle")

	vars := mux.Vars(r)
	reqBody, _ := ioutil.ReadAll(r.Body)

	id := vars["id"]
	for index, article := range Articles {
		if article.Id == id {
			var article Article
			json.Unmarshal(reqBody, &article)
			Articles[index].Id = article.Id
			Articles[index].Title = article.Title
			Articles[index].Desc = article.Desc
			Articles[index].Content = article.Content
			w.WriteHeader(http.StatusOK)
			w.Write([]byte("200  Update article successful"))
			json.NewEncoder(w).Encode(article)

		} else {
			log.Println("Record not found")
			w.WriteHeader(http.StatusInternalServerError)
			w.Write([]byte("500 - Delete article failed due to some error"))
		}
	}

}

//handleRequests() matches URL paths to defined function
func HandleRequests() {

	var m sync.Mutex

	myRouter := mux.NewRouter().StrictSlash(true)

	m.Lock()
	go myRouter.Handle("/api/v1/article", isAuthorized(createNewArticle)).Methods("POST")
	m.Unlock()

	m.Lock()
	go myRouter.Handle("/api/v2/article", isAuthorized(createNewArticleV2)).Methods("POST")
	m.Unlock()

	m.Lock()
	go myRouter.Handle("/api/v1/article/{id}", isAuthorized(updateArticle)).Methods("PUT")
	m.Unlock()
	myRouter.Handle("/api/v1", isAuthorized(homePage))
	myRouter.Handle("/api/v1/article", isAuthorized(returnArticles)).Methods("GET")
	myRouter.Handle("/api/v1/article/{id}", isAuthorized(returnSingleArticle)).Methods("GET")
	m.Lock()
	go myRouter.Handle("/api/v1/article/{id}", isAuthorized(deleteArticle)).Methods("DELETE")
	m.Unlock()

	log.Fatal(http.ListenAndServe(":10000", myRouter))
}

/*
// @title Swagger Example API
// @version 1.0
// @description This is a sample server celler server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1

// @securityDefinitions.basic BasicAuth

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

// @securitydefinitions.oauth2.application OAuth2Application
// @tokenUrl https://example.com/oauth/token
// @scope.write Grants write access
// @scope.admin Grants read and write access to administrative information

// @securitydefinitions.oauth2.implicit OAuth2Implicit
// @authorizationurl https://example.com/oauth/authorize
// @scope.write Grants write access
// @scope.admin Grants read and write access to administrative information

// @securitydefinitions.oauth2.password OAuth2Password
// @tokenUrl https://example.com/oauth/token
// @scope.read Grants read access
// @scope.write Grants write access
// @scope.admin Grants read and write access to administrative information

// @securitydefinitions.oauth2.accessCode OAuth2AccessCode
// @tokenUrl https://example.com/oauth/token
// @authorizationurl https://example.com/oauth/authorize
// @scope.admin Grants read and write access to administrative information

func main() {

	r := gin.Default()

	c := controller.NewController()

	v1 := r.Group("/api/v1")
	{
		accounts := v1.Group("/accounts")
		{
			accounts.GET(":id", c.ShowAccount)
			accounts.GET("", c.ListAccounts)
			accounts.POST("", c.AddAccount)
			accounts.DELETE(":id", c.DeleteAccount)
			accounts.PATCH(":id", c.UpdateAccount)
			accounts.POST(":id/images", c.UploadAccountImage)
		}
		//...
	}
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	r.Run(":8080")
	Articles = []Article{
		Article{Id: "1", Title: "Hello", Desc: "Article Description", Content: "Hello world!"},
		Article{Id: "2", Title: "Hello again", Desc: "Article Description", Content: "Hello world!!"},
	}
	handleRequests()
}*/
